version: '3.1'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: beerstore
      POSTGRES_PASSWORD: beerstore
      POSTGRES_DB: beerstore

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080